pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 카카오맵 SDK v2 (https://apis.map.kakao.com/android_v2/docs/getting-started/quickstart/)
        maven {
            url 'https://devrepo.kakao.com/nexus/repository/kakaomap-releases/'
            content {
                includeGroup 'com.kakao.maps.open'
            }
        }
    }
}

rootProject.name = "Jeongjungang"
include ':app'
